server:
  port: 10000
spring:
  application:
    name: scw-webui
  redis:
    host: redis1
    port: 6379
  session:
    store-type: redis
    timeout: 1800
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.offcn.webui: debug
feign:
  hystrix:
    enabled: true  #开启Feign的熔断功能
  client:
    config:
      default:
        connectTimeout: 5000  #连接超时时间2秒
        readTimeout: 5000     #读超时时间2秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #设置熔断时间20秒