server:
  port: 8761
spring:
  application:
    name: scw-register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000